### ISSUE TITLE
Add dependabot configuration

### ISSUE THREAD

**Issue by akalipetis** [withlogicco/django-prose#12]
We need to add dependabot configuration for Python and GitHub actions.

## Useful links:

* https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem

### Example for NPM for reference

```yaml
version: 2
updates:
  # Fetch and update latest `npm` packages
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      time: '00:00'
    open-pull-requests-limit: 10
    reviewers:
      - withlogicco/hq
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope

  # Fetch and update latest `github-actions` pkgs
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
      time: '00:00'
    open-pull-requests-limit: 10
    reviewers:
      - withlogicco/hq
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
```
